name: commands
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://openlibrary.org/api/books?bibkeys=ISBN:0201558025,LCCN:93005405&format=json
      
  
